### ISSUE TITLE
Fix Header sections

### ISSUE THREAD

**Issue by Kanav-Arora** [Kanav-Arora/TravelBuddy#98]
The header is not centred properly.

<img width="1440" alt="Screenshot 2024-04-06 at 11 37 28 AM" src="https://github.com/Kanav-Arora/tripzip/assets/62852363/8715543e-ec54-42d7-a2d7-117197a55438">

**Comment by Tashuuuu** [comment]
What has to be fixed in it?

**Comment by Kanav-Arora** [comment]
The middle section is not centered due to increased width of side sections so side section width should be same. In `LocationNavbar` side widths are 20%. Middle section should be 100% and justify-content as centre. So that even if the side elements changes the middle section should be centred.

You can check the LocationNavbar file and it would be better if you could shift to styled components by creating a style file.
For any queries feel free to ask. 
If you are interested I'll assign you the issue.

**Comment by Kanav-Arora** [comment]
Hi @Tashuuuu 
Are you working on this one?
